name = "ScalingCollapse"
uuid = "bcf2b353-04f3-4f78-ac0b-80007e341812"
authors = ["Malte PÃ¼tz"]
version = "0.2.4"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
KissSmoothing = "23b0397c-cd08-4270-956a-157331f0528f"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Dierckx = "0.5"
KissSmoothing = "1"
Measurements = "2"
Optim = "1.6.2"
Statistics = "1.9"
julia = "1.9"
