name = "Scaling"
uuid = "bcf2b353-04f3-4f78-ac0b-80007e341812"
authors = ["Malte PÃ¼tz"]
version = "0.3.1"

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
InteractiveScaling = "GLMakie"

[compat]
Dierckx = "0.5 - 0"
GLMakie = "0.9 - 0"
Measurements = "2"
Optim = "1.6.2"
Statistics = "1.9"
julia = "1.9"
